#db variables
HOST=
USER=
PASSWORD=
DATABASE=
PTERODACTYL_URL=
PTERODACTYL_ADMIN_KEY = 
PTERODACTYL_ADMIN_USER_KEY = 
STRIPE_API_KEY = 
# STRIPE_SECRET_KEY = 
STRIPE_SECRET_KEY = 
URL = 
YOUR_SUCCESS_URL = 
YOUR_CANCEL_URL = 
HOSTED_URL = URL