#db variables
HOST=
USER=
PASSWORD=
DATABASE=
PTERODACTYL_URL=
PTERODACTYL_ADMIN_KEY = 
PTERODACTYL_CLIENT_KEY = 
STRIPE_API_KEY = 
STRIPE_SECRET_KEY = 
URL = "http://127.0.0.1:3040/"
YOUR_SUCCESS_URL = f'{URL}store/success'
YOUR_CANCEL_URL = f'{URL}store/cancel'
HOSTED_URL = URL
SECRET_KEY =
MAIL_SERVER=
MAIL_PORT =
MAIL_USERNAME =
MAIL_PASSWORD = 
MAIL_DEFAULT_SENDER = 
RECAPTCHA_SITE_KEY = 
RECAPTCHA_SECRET_KEY =
WEBHOOK_URL =
#DISCORD BOT
ENABLE_BOT = True
TOKEN = 
DEBUG_FRONTEND_MODE =
AUTODEPLOY_NEST_ID: int = 
#DISCORD INVITE
DISCORD_INVITE = ""
DOWNLOAD_API_URL = ""
